export const ACTIONS = {
    "SET_STATE_TO_INITIAL": "SET_STATE_TO_INITIAL",
    "SET_ACTIVE_TAB": "SET_ACTIVE_TAB",
    "REMOVE_TAB_FROM_BAR": "REMOVE_TAB_FROM_BAR",
    "ADD_TAB_TO_BAR": "ADD_TAB_TO_BAR",
}